name: rtp-mil-cu128
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - torch==2.8.0
      - torchvision==0.23.0
      - numpy
      - scikit-learn
      - matplotlib
      - pandas
      - nibabel
